config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index]

  get '/support/:id', to: 'support#new', as: :support

  resources :checkouts, only: [:new, :create]
  authenticated :user do
    root 'dashboard#show', as: :authenticated_root
  end
  root 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reward_tier.rb
class RewardTier < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: { fan: 0, creator: 1 }
  has_many :reward_tiers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @tier = RewardTier.find(params[:tier_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :role)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def new
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @creators = User.creator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def user_avatar(email)
    image_tag("https://robohash.org/#{email}.png?size=128x128",class: 'media-object')
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkouts/new.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-1">
    <h1>Confirm your pledge to <%= @user.name %></h1>
    <div class="jumbotron">
      <h2>Your pledge to <%= @user.name %>: <%= number_to_currency(@tier.price) %></h2>
      <p><%= @tier.blurb %></p>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag 'https://robohash.org/sijsoijsoijs', size: '128x128' %>
    <p>Fake User</p>
    <h3>Supporting</h3>
    <p>You are not supporting anyone yet</p>
  </div>
  <div class="col-md-6">
    <div>

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist" id='myTabs'>
        <li role="presentation" class="active"><a href="#all-posts" aria-controls="all-posts" role="tab" data-toggle="tab">All posts</a></li>
        <li role="presentation"><a href="#patron-only-posts" aria-controls="patron-only-posts" role="tab" data-toggle="tab">Patron-only posts</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="all-posts">All posts</div>
        <div role="tabpanel" class="tab-pane" id="patron-only-posts">Patron-only</div>
      </div>

    </div>
    <div class="jumbotron">
      <p><%= link_to 'FIND CREATORS YOU LOVE', users_path, class: "btn btn-primary btn-lg", role: "button" %></p>
    </div>
  </div>
  <div class="col-md-3">
    <div>
      <h5>FIND CREATORS YOU LOVE</h5>
      <hr>
      <p><a class="btn btn-primary btn-sm" href="#" role="button">FIND CREATORS</a></p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1 class='centered text-upcase'>Creators, Come Get Paid</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fanco</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="page-header">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h1 class="root-link"><%= link_to 'Fanco', root_path %></h1>
          </div>
          <div class="col-md-8">
            <nav class="main-nav pull-right">
              <%= link_to 'Search', '' %>
              <%= link_to 'Start My Page', '' %>
              <%= link_to 'Explore Creators', '' %>
              <% if user_signed_in? %>
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path %>
                <%= link_to 'Log In', new_user_session_path %>
              <% end %>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <% flash.each do |type, message| %>
      <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fanco</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="page-header">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h1 class="root-link"><%= link_to 'Fanco', root_path %></h1>
          </div>
          <div class="col-md-8">
            <nav class="main-nav pull-right">
              <%= link_to 'Search', '' %>
              <%= link_to 'Start My Page', '' %>
              <%= link_to 'Explore Creators', '' %>
              <%= link_to 'Sign Up', new_user_registration_path %>
              <%= link_to 'Log In', new_user_session_path %>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-9 col-md-offset-1">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/support/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Support <%= @user.name %>!</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <div class="jumbotron">
      <h2>Choose your tier:</h2>
      <div class="row">
        <% @user.reward_tiers.each do |tier| %>
            <div class="col-md-4">
              <h2><%= tier.title %></h2>
              <hr>
              <p><%= tier.blurb %></p>
              <p><%= number_to_currency(tier.price) %></p>
              <p>Chosen <%= pluralize(tier.chosen_tally, 'time') %></p>
              <%= link_to 'Continue', new_checkout_path(user_id: @user.id, tier_id: tier.id), class: 'btn btn-success' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <h3>Creators</h3>
  <% @creators.each do |creator|%>
     <div class="media">
       <div class="media-left">
         <%= user_avatar(creator.email) %>
       </div>
       <div class="media-body">
         <%= creator.blurb %>
         <br>
         <%= link_to 'Support', support_path(creator.id), class: 'btn btn-primary' %>
       </div>

     </div>
    <p><%= creator.name %></p>
  <% end %>
</div>